<?php 
    $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
    $product = $objectManager->get('Magento\Framework\Registry')->registry('current_product'); 
?>
<div style="overflow-x:auto;">  
<table class="data-table">
	 <tbody>
		<tr>
		<th>Product Name</th>
		<td><?php echo $product->getName(); ?></td>  
		</tr>
		<tr>
		<th>Product Id</th>
		<td><a target="_blank" href="<?php echo "https://altitec.no/BBydD48cZyGPLcyP/catalog/product/edit/id/" . $product->getId(); ?>"><?php echo $product->getId(); ?></a></td>
		</tr>  
		<tr>
		<th>Product SKU</th>
		<td><?php echo $product->getSku(); ?></td>
		</tr> 
	 </tbody>
</table>
</div>
